title: Base de datos INAOE
description: Repositorio de asteroides 

theme: minima

minima:
  date_format: "%b %-d, %Y"
show_excerpts: true

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-mentions
